#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require File.dirname(__FILE__) + '/hql_types'

    module Hypertable
      module ThriftGen
  end
end
