#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift/protocol'
require File.dirname(__FILE__) + '/Client_types'


module Hypertable
  module ThriftGen
        class HqlResult
          include Thrift::Struct
          RESULTS = 1
          CELLS = 2
          SCANNER = 3
          MUTATOR = 4

          Thrift::Struct.field_accessor self, :results, :cells, :scanner, :mutator
          FIELDS = {
            RESULTS => {:type => Thrift::Types::LIST, :name => 'results', :element => {:type => Thrift::Types::STRING}, :optional => true},
            CELLS => {:type => Thrift::Types::LIST, :name => 'cells', :element => {:type => Thrift::Types::STRUCT, :class => Cell}, :optional => true},
            SCANNER => {:type => Thrift::Types::I64, :name => 'scanner', :optional => true},
            MUTATOR => {:type => Thrift::Types::I64, :name => 'mutator', :optional => true}
          }
          def validate
          end

        end

      end
    end
