/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class TableInputFormat_DummyRecordReader */

#ifndef _Included_TableInputFormat_DummyRecordReader
#define _Included_TableInputFormat_DummyRecordReader
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
