#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
import hyperthrift.gen.ClientService
from ttypes import *
from thrift.Thrift import TProcessor
from thrift.transport import TTransport
from thrift.protocol import TBinaryProtocol
try:
  from thrift.protocol import fastbinary
except:
  fastbinary = None


class Iface(hyperthrift.gen.ClientService.Iface):
  def hql_exec(self, command, noflush, unbuffered):
    pass


class Client(hyperthrift.gen.ClientService.Client, Iface):
  def __init__(self, iprot, oprot=None):
    hyperthrift.gen.ClientService.Client.__init__(self, iprot, oprot)

  def hql_exec(self, command, noflush, unbuffered):
    self.send_hql_exec(command, noflush, unbuffered)
    return self.recv_hql_exec()

  def send_hql_exec(self, command, noflush, unbuffered):
    self._oprot.writeMessageBegin('hql_exec', TMessageType.CALL, self._seqid)
    args = hql_exec_args()
    args.command = command
    args.noflush = noflush
    args.unbuffered = unbuffered
    args.write(self._oprot)
    self._oprot.writeMessageEnd()
    self._oprot.trans.flush()

  def recv_hql_exec(self, ):
    (fname, mtype, rseqid) = self._iprot.readMessageBegin()
    if mtype == TMessageType.EXCEPTION:
      x = TApplicationException()
      x.read(self._iprot)
      self._iprot.readMessageEnd()
      raise x
    result = hql_exec_result()
    result.read(self._iprot)
    self._iprot.readMessageEnd()
    if result.success != None:
      return result.success
    if result.e != None:
      raise result.e
    raise TApplicationException(TApplicationException.MISSING_RESULT, "hql_exec failed: unknown result");


class Processor(hyperthrift.gen.ClientService.Processor, Iface, TProcessor):
  def __init__(self, handler):
    hyperthrift.gen.ClientService.Processor.__init__(self, handler)
    self._processMap["hql_exec"] = Processor.process_hql_exec

  def process(self, iprot, oprot):
    (name, type, seqid) = iprot.readMessageBegin()
    if name not in self._processMap:
      iprot.skip(TType.STRUCT)
      iprot.readMessageEnd()
      x = TApplicationException(TApplicationException.UNKNOWN_METHOD, 'Unknown function %s' % (name))
      oprot.writeMessageBegin(name, TMessageType.EXCEPTION, seqid)
      x.write(oprot)
      oprot.writeMessageEnd()
      oprot.trans.flush()
      return
    else:
      self._processMap[name](self, seqid, iprot, oprot)
    return True

  def process_hql_exec(self, seqid, iprot, oprot):
    args = hql_exec_args()
    args.read(iprot)
    iprot.readMessageEnd()
    result = hql_exec_result()
    try:
      result.success = self._handler.hql_exec(args.command, args.noflush, args.unbuffered)
    except hyperthrift.gen.ttypes.ClientException, e:
      result.e = e
    oprot.writeMessageBegin("hql_exec", TMessageType.REPLY, seqid)
    result.write(oprot)
    oprot.writeMessageEnd()
    oprot.trans.flush()


# HELPER FUNCTIONS AND STRUCTURES

class hql_exec_args:

  thrift_spec = (
    None, # 0
    (1, TType.STRING, 'command', None, None, ), # 1
    (2, TType.BOOL, 'noflush', None, None, ), # 2
    (3, TType.BOOL, 'unbuffered', None, None, ), # 3
  )

  def __init__(self, d=None):
    self.command = None
    self.noflush = False
    self.unbuffered = False
    if isinstance(d, dict):
      if 'command' in d:
        self.command = d['command']
      if 'noflush' in d:
        self.noflush = d['noflush']
      if 'unbuffered' in d:
        self.unbuffered = d['unbuffered']

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 1:
        if ftype == TType.STRING:
          self.command = iprot.readString();
        else:
          iprot.skip(ftype)
      elif fid == 2:
        if ftype == TType.BOOL:
          self.noflush = iprot.readBool();
        else:
          iprot.skip(ftype)
      elif fid == 3:
        if ftype == TType.BOOL:
          self.unbuffered = iprot.readBool();
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('hql_exec_args')
    if self.command != None:
      oprot.writeFieldBegin('command', TType.STRING, 1)
      oprot.writeString(self.command)
      oprot.writeFieldEnd()
    if self.noflush != None:
      oprot.writeFieldBegin('noflush', TType.BOOL, 2)
      oprot.writeBool(self.noflush)
      oprot.writeFieldEnd()
    if self.unbuffered != None:
      oprot.writeFieldBegin('unbuffered', TType.BOOL, 3)
      oprot.writeBool(self.unbuffered)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __str__(self):
    return str(self.__dict__)

  def __repr__(self):
    return repr(self.__dict__)

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)

class hql_exec_result:

  thrift_spec = (
    (0, TType.STRUCT, 'success', (HqlResult, HqlResult.thrift_spec), None, ), # 0
    (1, TType.STRUCT, 'e', (hyperthrift.gen.ttypes.ClientException, hyperthrift.gen.ttypes.ClientException.thrift_spec), None, ), # 1
  )

  def __init__(self, d=None):
    self.success = None
    self.e = None
    if isinstance(d, dict):
      if 'success' in d:
        self.success = d['success']
      if 'e' in d:
        self.e = d['e']

  def read(self, iprot):
    if iprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and isinstance(iprot.trans, TTransport.CReadableTransport) and self.thrift_spec is not None and fastbinary is not None:
      fastbinary.decode_binary(self, iprot.trans, (self.__class__, self.thrift_spec))
      return
    iprot.readStructBegin()
    while True:
      (fname, ftype, fid) = iprot.readFieldBegin()
      if ftype == TType.STOP:
        break
      if fid == 0:
        if ftype == TType.STRUCT:
          self.success = HqlResult()
          self.success.read(iprot)
        else:
          iprot.skip(ftype)
      elif fid == 1:
        if ftype == TType.STRUCT:
          self.e = hyperthrift.gen.ttypes.ClientException()
          self.e.read(iprot)
        else:
          iprot.skip(ftype)
      else:
        iprot.skip(ftype)
      iprot.readFieldEnd()
    iprot.readStructEnd()

  def write(self, oprot):
    if oprot.__class__ == TBinaryProtocol.TBinaryProtocolAccelerated and self.thrift_spec is not None and fastbinary is not None:
      oprot.trans.write(fastbinary.encode_binary(self, (self.__class__, self.thrift_spec)))
      return
    oprot.writeStructBegin('hql_exec_result')
    if self.success != None:
      oprot.writeFieldBegin('success', TType.STRUCT, 0)
      self.success.write(oprot)
      oprot.writeFieldEnd()
    if self.e != None:
      oprot.writeFieldBegin('e', TType.STRUCT, 1)
      self.e.write(oprot)
      oprot.writeFieldEnd()
    oprot.writeFieldStop()
    oprot.writeStructEnd()

  def __str__(self):
    return str(self.__dict__)

  def __repr__(self):
    return repr(self.__dict__)

  def __eq__(self, other):
    return isinstance(other, self.__class__) and self.__dict__ == other.__dict__

  def __ne__(self, other):
    return not (self == other)


