:stats: {
        :cell_read_rate: { :pair: [:cell_read_rate],
                       :units: "" ,
                       :color: ["#edd400"],
                       :pname: "Cells Read"},
        :cell_write_rate: {
                       :pair: [:cell_write_rate],
                       :units: "" ,
                       :color: ["#73d216"],
                       :pname: "Cells Written"
                      },
        :byte_read_rate: { :pair: [:byte_read_rate],
                       :units: "bytes" ,
                       :color: ["#edd400"],
                       :pname: "Bytes Read"},
        :byte_write_rate: {
                       :pair: [:byte_write_rate],
                       :units: "bytes" ,
                       :color: ["#73d216"],
                       :pname: "Bytes Written"
                      },
        :bloom_filter_access: {
                       :pair: [:bloom_filter_access],
                       :units: "",
                       :color: ["#ad7fa8"],
                       :pname: "Bloom Filter Accesses"
                       },

        :bloom_filter_maybes: {
                       :pair:  [:bloom_filter_maybes],
                       :units: "",
                       :color: ["#73d216"],
                       :pname: "Bloom Filter Maybes"
                       },

        :bloom_filter_memory: {
                       :pair: [:bloom_filter_memory],
                       :units: "Bytes",
                       :color: ["#73d216"],
                       :pname: "Bloom Filter Memory"
                       },
        :block_index_memory: {
                       :pair: [ :block_index_memory],
                       :units: "Bytes",
                       :color: ["#5c3566"],
                       :pname: "Block Index Memory"
                       },

	:shadow_cache_memory: {
                       :pair: [ :shadow_cache_memory],
                       :units: "Bytes",
                       :color: ["#5c3566"],
                       :pname: "Shadow Cache Memory"
                       },

	:compression_ratio: {
                       :pair: [ :compression_ratio],
                       :units: "Bytes",
                       :color: ["#5c3566"],
                       :pname: "Compression Ratio"
                       },

        :scans: {
                      :pair: [:scans],
                      :units: "",
                      :color: ["#cc0000"],
                      :pname: "Scans"
                  },

        :disk_used: {
                       :pair: [:disk_used],
                       :units: "Bytes",
                       :color: ["#fcaf3e"],
                       :pname: "Disk Used"
                       },

        :memory_used: {
                      :pair: [:memory_used],
                      :units: "Bytes",
                      :color: ["#c17d11"],
                      :pname: "Memory Used"
                      },

		      
        :memory_allocated: {
                     :pair: [:memory_allocated],
                     :units: "Bytes",
                     :immutable: true,
                     :color: ["#888a85"],
                     :pname: "Memory Allocated"
                     },
	:updates: {
                      :pair: [:updates],
		      :units: "",
                      :color: ["#c17d11"],
                      :pname: "Updates"
                      }
}
