/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.hypertable.thriftgen;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.Set;
import java.util.HashSet;
import com.facebook.thrift.*;

import com.facebook.thrift.protocol.*;
import com.facebook.thrift.transport.*;

public class HqlService {

  /**
   * HQL service is a superset of Client service
   * 
   * It adds capability to execute HQL queries to the service
   */
  public interface Iface extends org.hypertable.thriftgen.ClientService.Iface {

    /**
     * Execute an HQL command
     * 
     * @param command - HQL command
     * 
     * @param noflush - Do not auto commit any modifications (return a mutator)
     * 
     * @param unbuffered - return a scanner instead of buffered results
     */
    public HqlResult hql_exec(String command, boolean noflush, boolean unbuffered) throws org.hypertable.thriftgen.ClientException, TException;

  }

  public static class Client extends org.hypertable.thriftgen.ClientService.Client implements Iface {
    public Client(TProtocol prot)
    {
      this(prot, prot);
    }

    public Client(TProtocol iprot, TProtocol oprot)
    {
      super(iprot, oprot);
    }

    public HqlResult hql_exec(String command, boolean noflush, boolean unbuffered) throws org.hypertable.thriftgen.ClientException, TException
    {
      send_hql_exec(command, noflush, unbuffered);
      return recv_hql_exec();
    }

    public void send_hql_exec(String command, boolean noflush, boolean unbuffered) throws TException
    {
      oprot_.writeMessageBegin(new TMessage("hql_exec", TMessageType.CALL, seqid_));
      hql_exec_args args = new hql_exec_args();
      args.command = command;
      args.noflush = noflush;
      args.unbuffered = unbuffered;
      args.write(oprot_);
      oprot_.writeMessageEnd();
      oprot_.getTransport().flush();
    }

    public HqlResult recv_hql_exec() throws org.hypertable.thriftgen.ClientException, TException
    {
      TMessage msg = iprot_.readMessageBegin();
      if (msg.type == TMessageType.EXCEPTION) {
        TApplicationException x = TApplicationException.read(iprot_);
        iprot_.readMessageEnd();
        throw x;
      }
      hql_exec_result result = new hql_exec_result();
      result.read(iprot_);
      iprot_.readMessageEnd();
      if (result.__isset.success) {
        return result.success;
      }
      if (result.__isset.e) {
        throw result.e;
      }
      throw new TApplicationException(TApplicationException.MISSING_RESULT, "hql_exec failed: unknown result");
    }

  }
  public static class Processor extends org.hypertable.thriftgen.ClientService.Processor implements TProcessor {
    public Processor(Iface iface)
    {
      super(iface);
      iface_ = iface;
      processMap_.put("hql_exec", new hql_exec());
    }

    private Iface iface_;

    public boolean process(TProtocol iprot, TProtocol oprot) throws TException
    {
      TMessage msg = iprot.readMessageBegin();
      ProcessFunction fn = processMap_.get(msg.name);
      if (fn == null) {
        TProtocolUtil.skip(iprot, TType.STRUCT);
        iprot.readMessageEnd();
        TApplicationException x = new TApplicationException(TApplicationException.UNKNOWN_METHOD, "Invalid method name: '"+msg.name+"'");
        oprot.writeMessageBegin(new TMessage(msg.name, TMessageType.EXCEPTION, msg.seqid));
        x.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
        return true;
      }
      fn.process(msg.seqid, iprot, oprot);
      return true;
    }

    private class hql_exec implements ProcessFunction {
      public void process(int seqid, TProtocol iprot, TProtocol oprot) throws TException
      {
        hql_exec_args args = new hql_exec_args();
        args.read(iprot);
        iprot.readMessageEnd();
        hql_exec_result result = new hql_exec_result();
        try {
          result.success = iface_.hql_exec(args.command, args.noflush, args.unbuffered);
          result.__isset.success = true;
        } catch (org.hypertable.thriftgen.ClientException e) {
          result.e = e;
          result.__isset.e = true;
        }
        oprot.writeMessageBegin(new TMessage("hql_exec", TMessageType.REPLY, seqid));
        result.write(oprot);
        oprot.writeMessageEnd();
        oprot.getTransport().flush();
      }

    }

  }

  public static class hql_exec_args implements TBase, java.io.Serializable, Cloneable   {
    public String command;
    public static final int COMMAND = 1;
    public boolean noflush;
    public static final int NOFLUSH = 2;
    public boolean unbuffered;
    public static final int UNBUFFERED = 3;

    public final Isset __isset = new Isset();
    public static final class Isset implements java.io.Serializable {
      public boolean command = false;
      public boolean noflush = false;
      public boolean unbuffered = false;
    }

    public hql_exec_args() {
      this.noflush = false;

      this.unbuffered = false;

    }

    public hql_exec_args(
      String command,
      boolean noflush,
      boolean unbuffered)
    {
      this();
      this.command = command;
      this.__isset.command = (command != null);
      this.noflush = noflush;
      this.__isset.noflush = true;
      this.unbuffered = unbuffered;
      this.__isset.unbuffered = true;
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public hql_exec_args(hql_exec_args other) {
      __isset.command = other.__isset.command;
      if (other.command != null) {
        this.command = other.command;
      }
      __isset.noflush = other.__isset.noflush;
      this.noflush = other.noflush;
      __isset.unbuffered = other.__isset.unbuffered;
      this.unbuffered = other.unbuffered;
    }

    public hql_exec_args clone() {
      return new hql_exec_args(this);
    }

    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof hql_exec_args)
        return this.equals((hql_exec_args)that);
      return false;
    }

    public boolean equals(hql_exec_args that) {
      if (that == null)
        return false;

      boolean this_present_command = true && (this.command != null);
      boolean that_present_command = true && (that.command != null);
      if (this_present_command || that_present_command) {
        if (!(this_present_command && that_present_command))
          return false;
        if (!this.command.equals(that.command))
          return false;
      }

      boolean this_present_noflush = true;
      boolean that_present_noflush = true;
      if (this_present_noflush || that_present_noflush) {
        if (!(this_present_noflush && that_present_noflush))
          return false;
        if (this.noflush != that.noflush)
          return false;
      }

      boolean this_present_unbuffered = true;
      boolean that_present_unbuffered = true;
      if (this_present_unbuffered || that_present_unbuffered) {
        if (!(this_present_unbuffered && that_present_unbuffered))
          return false;
        if (this.unbuffered != that.unbuffered)
          return false;
      }

      return true;
    }

    public int hashCode() {
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case COMMAND:
            if (field.type == TType.STRING) {
              this.command = iprot.readString();
              this.__isset.command = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case NOFLUSH:
            if (field.type == TType.BOOL) {
              this.noflush = iprot.readBool();
              this.__isset.noflush = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case UNBUFFERED:
            if (field.type == TType.BOOL) {
              this.unbuffered = iprot.readBool();
              this.__isset.unbuffered = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields
    }

    public void write(TProtocol oprot) throws TException {


      TStruct struct = new TStruct("hql_exec_args");
      oprot.writeStructBegin(struct);
      TField field = new TField();
      if (this.command != null) {
        field.name = "command";
        field.type = TType.STRING;
        field.id = COMMAND;
        oprot.writeFieldBegin(field);
        oprot.writeString(this.command);
        oprot.writeFieldEnd();
      }
      field.name = "noflush";
      field.type = TType.BOOL;
      field.id = NOFLUSH;
      oprot.writeFieldBegin(field);
      oprot.writeBool(this.noflush);
      oprot.writeFieldEnd();
      field.name = "unbuffered";
      field.type = TType.BOOL;
      field.id = UNBUFFERED;
      oprot.writeFieldBegin(field);
      oprot.writeBool(this.unbuffered);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public String toString() {
      StringBuilder sb = new StringBuilder("hql_exec_args(");
      boolean first = true;

      if (!first) sb.append(", ");
      sb.append("command:");
      sb.append(this.command);
      first = false;
      if (!first) sb.append(", ");
      sb.append("noflush:");
      sb.append(this.noflush);
      first = false;
      if (!first) sb.append(", ");
      sb.append("unbuffered:");
      sb.append(this.unbuffered);
      first = false;
      sb.append(")");
      return sb.toString();
    }

  }

  public static class hql_exec_result implements TBase, java.io.Serializable, Cloneable   {
    public HqlResult success;
    public static final int SUCCESS = 0;
    public org.hypertable.thriftgen.ClientException e;
    public static final int E = 1;

    public final Isset __isset = new Isset();
    public static final class Isset implements java.io.Serializable {
      public boolean success = false;
      public boolean e = false;
    }

    public hql_exec_result() {
    }

    public hql_exec_result(
      HqlResult success,
      org.hypertable.thriftgen.ClientException e)
    {
      this();
      this.success = success;
      this.__isset.success = (success != null);
      this.e = e;
      this.__isset.e = (e != null);
    }

    /**
     * Performs a deep copy on <i>other</i>.
     */
    public hql_exec_result(hql_exec_result other) {
      __isset.success = other.__isset.success;
      if (other.success != null) {
        this.success = new HqlResult(other.success);
      }
      __isset.e = other.__isset.e;
      if (other.e != null) {
        this.e = new org.hypertable.thriftgen.ClientException(other.e);
      }
    }

    public hql_exec_result clone() {
      return new hql_exec_result(this);
    }

    public boolean equals(Object that) {
      if (that == null)
        return false;
      if (that instanceof hql_exec_result)
        return this.equals((hql_exec_result)that);
      return false;
    }

    public boolean equals(hql_exec_result that) {
      if (that == null)
        return false;

      boolean this_present_success = true && (this.success != null);
      boolean that_present_success = true && (that.success != null);
      if (this_present_success || that_present_success) {
        if (!(this_present_success && that_present_success))
          return false;
        if (!this.success.equals(that.success))
          return false;
      }

      boolean this_present_e = true && (this.e != null);
      boolean that_present_e = true && (that.e != null);
      if (this_present_e || that_present_e) {
        if (!(this_present_e && that_present_e))
          return false;
        if (!this.e.equals(that.e))
          return false;
      }

      return true;
    }

    public int hashCode() {
      return 0;
    }

    public void read(TProtocol iprot) throws TException {
      TField field;
      iprot.readStructBegin();
      while (true)
      {
        field = iprot.readFieldBegin();
        if (field.type == TType.STOP) { 
          break;
        }
        switch (field.id)
        {
          case SUCCESS:
            if (field.type == TType.STRUCT) {
              this.success = new HqlResult();
              this.success.read(iprot);
              this.__isset.success = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          case E:
            if (field.type == TType.STRUCT) {
              this.e = new org.hypertable.thriftgen.ClientException();
              this.e.read(iprot);
              this.__isset.e = true;
            } else { 
              TProtocolUtil.skip(iprot, field.type);
            }
            break;
          default:
            TProtocolUtil.skip(iprot, field.type);
            break;
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields
    }

    public void write(TProtocol oprot) throws TException {
      TStruct struct = new TStruct("hql_exec_result");
      oprot.writeStructBegin(struct);
      TField field = new TField();

      if (this.__isset.success) {
        if (this.success != null) {
          field.name = "success";
          field.type = TType.STRUCT;
          field.id = SUCCESS;
          oprot.writeFieldBegin(field);
          this.success.write(oprot);
          oprot.writeFieldEnd();
        }
      } else if (this.__isset.e) {
        if (this.e != null) {
          field.name = "e";
          field.type = TType.STRUCT;
          field.id = E;
          oprot.writeFieldBegin(field);
          this.e.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

    public String toString() {
      StringBuilder sb = new StringBuilder("hql_exec_result(");
      boolean first = true;

      if (!first) sb.append(", ");
      sb.append("success:");
      sb.append(this.success);
      first = false;
      if (!first) sb.append(", ");
      sb.append("e:");
      sb.append(this.e);
      first = false;
      sb.append(")");
      return sb.toString();
    }

  }

}
