/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Client_CONSTANTS_H
#define Client_CONSTANTS_H

#include "Client_types.h"

namespace Hypertable { namespace ThriftGen {

class ClientConstants {
 public:
  ClientConstants();

};

extern const ClientConstants g_Client_constants;

}} // namespace

#endif
