/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Hql_CONSTANTS_H
#define Hql_CONSTANTS_H

#include "Hql_types.h"

namespace Hypertable { namespace ThriftGen {

class HqlConstants {
 public:
  HqlConstants();

};

extern const HqlConstants g_Hql_constants;

}} // namespace

#endif
