UPDATE Test2 "Test2-data.txt";
CREATE SCANNER ON Test2[..??] WHERE ROW >= "Abama" LIMIT=4;
DESTROY SCANNER;
CREATE SCANNER ON Test2[..??] WHERE ROW >= "Abama" LIMIT=2 MAX_VERSIONS=1;
DESTROY SCANNER;
quit
