UPDATE Test1 "Test1-data.txt";
CREATE SCANNER ON Test1[..??];
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE ROW = "Agamemnon";
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE ROW >= "Agamemnon" LIMIT=5;
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE "Agamemnon" <= ROW <= "Agamemnon";
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE "Agamemnon" <= ROW <= "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE "Agamemnon" < ROW <= "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE "Agamemnon" <= ROW < "Aganice";
DESTROY SCANNER;
CREATE SCANNER ON Test1[..??] WHERE "Agamemnon" < ROW < "Aganice";
DESTROY SCANNER;
quit;
